### ISSUE TITLE
Rainbow Six Extraction support

### ISSUE THREAD

**Issue by Ryhon0** [parzivail/RainbowForge#17]
Will this program get support for R6E? It seems to list files alright but clicking on anything throws `No constructor for container 150 of style 0x57FBAA36` [here](https://github.com/parzivail/RainbowForge/blob/master/RainbowForge/Core/Forge.cs#L184).

I have 5 invites for the test server that I could give out to anyone who's interested

**Comment by parzivail** [comment]
I preloaded R6E TT2 yesterday, and have been working with TT1 as well to provide support ASAP. No concrete timeline yet but I'm definitely working on it. I'll keep this issue open until it's ready.

**Comment by parzivail** [comment]
Alright, support is here with one catch: you need to have a binary of the Oodle compression library (`oo2core_8_win64.dll`) somewhere. Make sure to set the environment variable `OODLE2_8_PATH` to the path of that dll.
