### ISSUE TITLE
DumpTool fails to dump certain assets

### ISSUE THREAD

**Issue by kran27** [parzivail/RainbowForge#24]
DumpTool will fail to dump assets such as GlobalMetaFile and FastLoadDataTOC because they aren't recognized as ForgeAssets, Prism has no issue dumping these files.

**Comment by parzivail** [comment]
DumpTool is deprecated, I only keep it around for posterity. Please use Prism where possible

**Comment by kran27** [comment]
readme should probably be updated to say that, and have something saying what each of the projects are for
